### ISSUE TITLE
PCIe board: RuntimeError: Error reading at 0xf0000010 len: 4 errno(110): Connection timed out

### ISSUE THREAD

**Issue by erdalkaraca** [Brainchip-Inc/akida_dw_edma#16]
Hi,
I followed the latest driver installation manual on the support page.
After the driver compiled and loaded successfully, I run

```
> akida devices
RuntimeError: Error reading at 0xf0000010 len: 4 errno(110): Connection timed out
```

My env:
- OS: Ubuntu 22.04.4
- CPU: AMD Ryzen 3955WX
- Python 10 and 11 (via conda envs)

The PCIe board is listed:
```
> lspcie | grep Co-proc
06:10.0 Co-processor: Brainchip Inc AKD1000 Neural Network Coprocessor [Akida] (rev 01)
```

**Comment by rchevalier-brainchip** [comment]
Hi Erdal,

the message you see indicates that the Akida system is a bad shape; this may happen the first time on a fresh install.
I would recommend to reset it (PC warm boot for ex:).
For further assistance do to hesitate to go through https://support.brainchip.com/portal/en/signin

Best,
RC

**Comment by erdalkaraca** [comment]
Hi all,
The issue seems to be related to my initial hardware setup. I tried another hardware setup and akida devices lists my pcie board.
Thanks for your support.
