### ISSUE TITLE
Multiple Device Support

### ISSUE THREAD

**Issue by researcher2** [Brainchip-Inc/akida_dw_edma#3]
Hello!

I have a single device working and was interested in trying larger models using multiple NSOC in series but the installer doesn't seem to do this by default.

They both show up with lspci but I only see a single device when running "akida devices".

Thanks

**Comment by tengomucho** [comment]
Hi,

multiple device feature is not implemented yet. Note that current akida runtime allows to use models that do not fit entirely on a single board reconfiguring the HW transparently.
Could you please share more details regarding your targeted use case through https://brainchipinc.com/support/ ?

Thanks
